### ISSUE TITLE
error in Empire 2.0

### ISSUE THREAD

**Issue by LIZySARA** [minisllc/red-team-scripts#1]
[!] Invalid module or agent language version: 'MinLanguageVersion'
Windows 7 pro

![empire 2 0](https://user-images.githubusercontent.com/22563762/27939964-cfbe4918-62bf-11e7-8479-2cd5dc0e083f.png)

**Comment by andrewchiles** [comment]
I'm guessing you figured out the issue since you closed it? It looks like you might be running the module on a non-Windows host? I haven't tested with the most recent release of Empire so there could be other issues.

**Comment by LIZySARA** [comment]
Yes yes I understood the problem I just replaced "MinPSVersion" by "MinLanguageVersion" in the hostenum.py on Empire 2.0 
![ps](https://user-images.githubusercontent.com/22563762/28095293-99aec8e2-6699-11e7-9b6f-fe977cff2a59.png)
![pss](https://user-images.githubusercontent.com/22563762/28095297-9c58e352-6699-11e7-9c65-631fc88b3fec.png)

There is a problem of execution under windows 7
![7](https://user-images.githubusercontent.com/22563762/28095381-fd0cb304-6699-11e7-9364-2f039e7ac123.png)

Under Windows 8.1 Pro it passes without problem except the path when you fill it it leaves an error
![path](https://user-images.githubusercontent.com/22563762/28095466-76918740-669a-11e7-85f0-2431f3ba8dad.png)


The result without the patch
![propre](https://user-images.githubusercontent.com/22563762/28095480-84abe69a-669a-11e7-90a2-d6f2469f21fa.png)

**Comment by andrewchiles** [comment]
Thank you for the detailed descriptions and screenshots. The ```"MinPSVersion"``` vs ```"MinLanguageVersion" ```  is a new module style for Empire 2.0 which accommodates python and powershell based post modules.  I've now updated the module source based on the new 2.0 template and set the module to operate in the background so it doesn't block the agent during long execution times.

Regarding the optional ```Path``` parameter  for an HTML formatted output file. The path is relative to the target Windows host. The error you're seeing is due to the path failing a validation test on the target host. If a value is specified for  ```Path```, the script will ensure that path exists and is writeable before continuing execution. After execution, the file would then need to be manually downloaded and removed from the target. I just played with using the built-in Empire function to save module output to a file, but the returned file was garbled for some reason. That will take some more work to get the built-in Empire output saving to work.

Using these recent changes, I tested code execution in Windows 7 SP1 64bit and Windows 10 without issue. I'm going to close this issue for now, but if you have lingering issues feel free to create a new issue.

Thanks again! - Andrew
